---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download

- hosts: master
  become: yes
  roles:
    - role: k3s/master
    # - role: azcli
    - role: fluxcd
    # - role: k3s/node

- hosts: node
  become: yes
  roles:
    # - role: k3s/node
    - role: azcli