---
# - name: Print all available facts
#   ansible.builtin.debug:
#     msg: "{{ ansible_os_family }}"

- name: Install az cli prereq for Debian
  ansible.builtin.package:
    name:
      - ca-certificates 
      - curl 
      - apt-transport-https 
      - lsb-release 
      - gnupg
    state: present
  when: ansible_os_family == "Debian"

- name: Install keys on Debian
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

# - name: Install keys on Debian
#   become: true
#   ansible.builtin.shell: |
#     curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
#     AZ_REPO=$(lsb_release -cs)
#     echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
#   when: ansible_os_family == "Debian"

- name: Install az cli for Debian
  ansible.builtin.apt:
    name:
      - azure-cli
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"