---


- hosts: all
  connection: local
  become: true
  roles:
    - role: azcli

- hosts: k3s_cluster
  connection: local
  become: true
  roles:
    - role: k3s/prereq
    - role: k3s/download
  vars:
    k3s_version: v1.22.3+k3s1

- hosts: master
  connection: local
  become: true
  roles:
    - role: k3s/master
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    systemd_dir: /etc/systemd/system
    master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""
