---
- hosts: all
  connection: local
  become: true
  roles:
    - role: azcli
    # - role: vault-test

# - hosts: k3s_cluster
#   connection: local
#   become: true
#   roles:
#     - role: k3s/prereq
#     - role: k3s/download

# - hosts: master
#   connection: local
#   become: true
#   roles:
#     - role: k3s/master

# - hosts: gitops
#   connection: local
#   become: true
#   roles:
#     - role: fluxcd