---
azure:
  service_principal_id: "<SERVICE PRINCIPAL ID>"
  service_principal_secret: "<SERVICE PRINCIPAL SECRET>"
  resource_group: "azure-arc-rg"
  tenant_id: "<TENANT ID>"
  subscription_id: "<SUBSCRIPTION ID>"
  location: 'WestEurope'

kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"